apiVersion: v1
kind: Namespace
metadata:
  name: healthcare
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: healthcare
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
