name: Build and Push to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/ecr-build-push.yml'

env:
  AWS_REGION: us-east-1
  BACKEND_REPO: healthcare-backend
  FRONTEND_REPO: healthcare-frontend

permissions:
  contents: read

jobs:
  login-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build backend image
        working-directory: ./backend
        run: |
          IMAGE_TAG=${{ github.sha }}
          REPO_URI=$(aws ecr describe-repositories --repository-names $BACKEND_REPO --region $AWS_REGION --query "repositories[0].repositoryUri" --output text)
          docker build -t ${REPO_URI}:$IMAGE_TAG .
          docker push ${REPO_URI}:$IMAGE_TAG

      - name: Build frontend image
        working-directory: ./frontend
        run: |
          IMAGE_TAG=${{ github.sha }}
          REPO_URI=$(aws ecr describe-repositories --repository-names $FRONTEND_REPO --region $AWS_REGION --query "repositories[0].repositoryUri" --output text)
          docker build -t ${REPO_URI}:$IMAGE_TAG .
          docker push ${REPO_URI}:$IMAGE_TAG
